apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-api
  template:
    metadata:
      labels:
        app: cloud-api
    spec:
      containers:
        - name: cloud-api
          image: nginx:latest
          ports:
            - containerPort: 3000
